<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<RootNamespace>process_menu_upload_function</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CloudNative.CloudEvents" Version="2.8.0" />
		<PackageReference Include="Google.Cloud.Firestore" Version="4.2.0" />
		<PackageReference Include="Google.Cloud.Functions.Hosting" Version="3.0.1" />
		<PackageReference Include="Google.Cloud.Vision.V1" Version="3.8.0" />
		<PackageReference Include="Google.Events.Protobuf" Version="1.8.0" />
	</ItemGroup>
</Project>